artifact_uri: file:///Users/manarfarghaly/Desktop/Data/senior2firstterm/datascience/AccidentSeverity/Accident-Severity-Prediction/mlruns/0/7bbceed5bc1946cc99ba99c4b6af897e/artifacts
end_time: 1777819161969
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 7bbceed5bc1946cc99ba99c4b6af897e
run_uuid: 7bbceed5bc1946cc99ba99c4b6af897e
source_name: ''
source_type: 4
source_version: ''
start_time: 1777819160428
status: 3
tags: []
user_id: manarfarghaly
