artifact_uri: file:///Users/manarfarghaly/Desktop/Data/senior2firstterm/datascience/AccidentSeverity/Accident-Severity-Prediction/mlruns/0/9ccc2d00099749219a2738302edd7c4e/artifacts
end_time: 1777819769225
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9ccc2d00099749219a2738302edd7c4e
run_uuid: 9ccc2d00099749219a2738302edd7c4e
source_name: ''
source_type: 4
source_version: ''
start_time: 1777819767226
status: 3
tags: []
user_id: manarfarghaly
