artifact_uri: file:///Users/manarfarghaly/Desktop/Data/senior2firstterm/datascience/AccidentSeverity/Accident-Severity-Prediction/mlruns/0/72659fcd872148cbb58dd01ef37d7902/artifacts
end_time: 1777828088110
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 72659fcd872148cbb58dd01ef37d7902
run_uuid: 72659fcd872148cbb58dd01ef37d7902
source_name: ''
source_type: 4
source_version: ''
start_time: 1777828083098
status: 3
tags: []
user_id: manarfarghaly
