artifact_uri: file:///Users/manarfarghaly/Desktop/Data/senior2firstterm/datascience/AccidentSeverity/Accident-Severity-Prediction/mlruns/0/cafb6989dc0642fd9bcc204c7b62f215/artifacts
end_time: 1777819784546
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: cafb6989dc0642fd9bcc204c7b62f215
run_uuid: cafb6989dc0642fd9bcc204c7b62f215
source_name: ''
source_type: 4
source_version: ''
start_time: 1777819783032
status: 3
tags: []
user_id: manarfarghaly
