artifact_uri: file:///Users/manarfarghaly/Desktop/Data/senior2firstterm/datascience/AccidentSeverity/Accident-Severity-Prediction/mlruns/0/aff2a81782e245b88c7434552ffb590d/artifacts
end_time: 1777825290120
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: aff2a81782e245b88c7434552ffb590d
run_uuid: aff2a81782e245b88c7434552ffb590d
source_name: ''
source_type: 4
source_version: ''
start_time: 1777825280435
status: 3
tags: []
user_id: manarfarghaly
