artifact_uri: file:///Users/manarfarghaly/Desktop/Data/senior2firstterm/datascience/AccidentSeverity/Accident-Severity-Prediction/mlruns/0/549407da06b04e9abbff1bc556e7f9bc/artifacts
end_time: 1777825108613
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 549407da06b04e9abbff1bc556e7f9bc
run_uuid: 549407da06b04e9abbff1bc556e7f9bc
source_name: ''
source_type: 4
source_version: ''
start_time: 1777825101207
status: 3
tags: []
user_id: manarfarghaly
