artifact_uri: file:///Users/manarfarghaly/Desktop/Data/senior2firstterm/datascience/AccidentSeverity/Accident-Severity-Prediction/mlruns/0/379332ba6109444491adbcee5bbfa885/artifacts
end_time: 1777828489431
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 379332ba6109444491adbcee5bbfa885
run_uuid: 379332ba6109444491adbcee5bbfa885
source_name: ''
source_type: 4
source_version: ''
start_time: 1777828481437
status: 3
tags: []
user_id: manarfarghaly
