artifact_uri: file:///Users/manarfarghaly/Desktop/Data/senior2firstterm/datascience/AccidentSeverity/Accident-Severity-Prediction/mlruns/0/ad25d001a5b04ef7b70caabd6e676375/artifacts
end_time: 1777827452514
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ad25d001a5b04ef7b70caabd6e676375
run_uuid: ad25d001a5b04ef7b70caabd6e676375
source_name: ''
source_type: 4
source_version: ''
start_time: 1777827443566
status: 3
tags: []
user_id: manarfarghaly
