artifact_uri: file:///Users/manarfarghaly/Desktop/Data/senior2firstterm/datascience/AccidentSeverity/Accident-Severity-Prediction/mlruns/0/f74ffce21e2144369cec3903e9bdb58b/artifacts
end_time: 1777824442269
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f74ffce21e2144369cec3903e9bdb58b
run_uuid: f74ffce21e2144369cec3903e9bdb58b
source_name: ''
source_type: 4
source_version: ''
start_time: 1777824440276
status: 3
tags: []
user_id: manarfarghaly
