artifact_uri: file:///Users/manarfarghaly/Desktop/Data/senior2firstterm/datascience/AccidentSeverity/Accident-Severity-Prediction/mlruns/0/7853e8cfd86a4c5388dc9b105e157550/artifacts
end_time: 1777808031563
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 7853e8cfd86a4c5388dc9b105e157550
run_uuid: 7853e8cfd86a4c5388dc9b105e157550
source_name: ''
source_type: 4
source_version: ''
start_time: 1777808029224
status: 3
tags: []
user_id: manarfarghaly
